"""
Shared pytest fixtures.

The proofs in fixtures.json are REAL Groth16 proofs generated by snarkjs against
the circuits in this repo (see the generator in the git history / e2e script).
Committing them means the backend test suite verifies genuine cryptography
without needing Node or snarkjs installed in the Python CI job.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

import pytest

# Point the verifier at the real keys before any backend module is imported.
os.environ.setdefault(
    "CIRCUIT_KEYS_DIR",
    str(Path(__file__).resolve().parent.parent.parent / "circuits" / "keys"),
)

# The committed proofs in fixtures.json were generated with current date
# 2026-07-15. Pin the verifier's notion of "today" to that so the age-freshness
# check is deterministic no matter when the suite runs. See _reference_today().
os.environ.setdefault("ZKGATE_REFERENCE_DATE", "2026-07-15")

FIXTURES = json.loads((Path(__file__).parent / "fixtures.json").read_text())


@pytest.fixture
def proofs():
    return FIXTURES


@pytest.fixture
def client():
    """A fresh TestClient with reset registries, so tests don't leak nullifiers
    into each other."""
    from fastapi.testclient import TestClient

    import dependencies
    from services.audit_logger import AuditLogger
    from services.nullifier_registry import NullifierRegistry
    from services.verifier_registry import VerifierRegistry

    dependencies.nullifiers = NullifierRegistry(None)
    dependencies.audit = AuditLogger()
    dependencies.verifiers = VerifierRegistry()

    from main import app

    return TestClient(app)


def bundle(proof_entry, claim_type, *, demo=True, verifier_id="99999", expected=None):
    return {
        "proof_bundle": {
            "proof": proof_entry["proof"],
            "public_signals": proof_entry["public_signals"],
            "claim_type": claim_type,
            "generated_at": 1783699000,
            "demo": demo,
        },
        "verifier_id": verifier_id,
        "expected": expected or {},
    }
