#!/usr/bin/env node
/**
 * Regenerate every entry in backend/tests/fixtures.json against the current
 * circuits — real Groth16 proofs generated by snarkjs, not hand-edited JSON.
 * Run this any time a circuit's public-signal layout or witness shape
 * changes (see backend/tests/conftest.py's docstring on why fixtures.json is
 * committed instead of generated at test time).
 *
 * Prereq: npm run build:circuits must have already produced fresh
 * circuits/build/*.wasm and circuits/keys/*_final.zkey.
 *
 * Usage: node scripts/regenerate_fixtures.mjs
 */
import fs from "node:fs";
import path from "node:path";
import { groth16 } from "snarkjs";
import { parseAadhaarXml } from "../sdk/src/aadhaar.js";
import { deriveSecret, buildWitness } from "../sdk/src/prover.js";
import {
  loadOrCreateIssuerKey, issueAgeCredential, issueLocationCredential,
  issueCitizenshipCredential, issueCompoundCredential,
} from "./issuer/issue_credential.mjs";

const ROOT = new URL("..", import.meta.url).pathname.replace(/^\/([A-Za-z]):/, "$1:");
const SAMPLE = fs.readFileSync(path.join(ROOT, "test-data/sample_aadhaar.xml"), "utf8");
const KEYS = path.join(ROOT, "circuits/keys");
const BUILD = path.join(ROOT, "circuits/build");
const FIXTURES_PATH = path.join(ROOT, "backend/tests/fixtures.json");

// Match the pinned ZKGATE_REFERENCE_DATE in backend/tests/conftest.py so the
// freshness check in proof_verifier.py stays deterministic. Update both
// together if this ever changes.
const REF = { current_year: 2026, current_month: 7, current_day: 15 };
const VERIFIER_ID = "99999";
// A session-expiry timestamp deliberately far in the future (2035-07-15). The
// backend derives the nullifier's replay-registry TTL from this (expiry - now),
// so a past value would clamp the TTL to ~1s and make the replay tests flaky.
// The circuits only fold expiry into the nullifier hash; they never compare it
// against the current date, so any value is cryptographically fine.
const EXPIRY = 2068070400;

const wasmZkey = (circuitDir, snake) => ({
  wasm: path.join(BUILD, circuitDir, `${circuitDir}_js`, `${circuitDir}.wasm`),
  zkey: path.join(KEYS, `${snake}_final.zkey`),
});

const parsed = parseAadhaarXml(SAMPLE);
const secret = await deriveSecret(parsed.raw.referenceId);
const prvKey = loadOrCreateIssuerKey(path.join(ROOT, "scripts/issuer/demo_issuer_key.json"));

async function build(claimType, circuitDir, snake, witnessExtra, issuerCredential) {
  const witness = buildWitness({
    claimType, fields: parsed.fields, secret,
    request: { verifierId: VERIFIER_ID, expiry: EXPIRY, ...witnessExtra },
    issuerCredential,
  });
  // Only the age/compound circuits take a current-date input; pin it to the
  // reference date so those fixtures stay deterministic against conftest.py's
  // ZKGATE_REFERENCE_DATE. The location/citizen/pan circuits declare no such
  // signal, so blindly injecting one makes circom reject the witness with
  // "Too many values for input signal current_year".
  if ("current_year" in witness) Object.assign(witness, REF);
  const { wasm, zkey } = wasmZkey(circuitDir, snake);
  const { proof, publicSignals } = await groth16.fullProve(witness, wasm, zkey);
  return { proof, public_signals: publicSignals, claim: snake };
}

const fixtures = JSON.parse(fs.readFileSync(FIXTURES_PATH, "utf8"));

// age18 / age21
const ageCred = await issueAgeCredential(prvKey, {
  dob_year: parsed.fields.dob_year, dob_month: parsed.fields.dob_month,
  dob_day: parsed.fields.dob_day, secret,
});
fixtures.age18 = await build("age_above_18", "ageProof", "age_proof", { ageThreshold: 18 }, ageCred);
fixtures.age21 = await build("age_above_21", "ageProof", "age_proof", { ageThreshold: 21 }, ageCred);

// locAP (state_resident, Andhra Pradesh)
const locCred = await issueLocationCredential(prvKey, {
  state_code: parsed.fields.state_code, district_code: parsed.fields.district_code,
  pincode: parsed.fields.pincode, secret,
});
fixtures.locAP = await build(
  "state_resident", "locationProof", "location_proof",
  { requiredStateCode: 28, requiredDistrictCode: 0, requiredPincode: 0, proofLevel: 2 },
  locCred,
);

// citizen (india_citizen)
const citCred = await issueCitizenshipCredential(prvKey, { secret });
fixtures.citizen = await build("india_citizen", "citizenshipProof", "citizenship_proof", {}, citCred);

// kyc (compound_kyc)
const kycCred = await issueCompoundCredential(prvKey, {
  dob_year: parsed.fields.dob_year, dob_month: parsed.fields.dob_month, dob_day: parsed.fields.dob_day,
  state_code: parsed.fields.state_code, district_code: parsed.fields.district_code, secret,
});
fixtures.kyc = await build(
  "compound_kyc", "compoundProof", "compound_proof",
  { ageThreshold: 18, requiredStateCode: 28, requiredDistrictCode: 0 },
  kycCred,
);

fs.writeFileSync(FIXTURES_PATH, JSON.stringify(fixtures, null, 2) + "\n");
for (const k of ["age18", "age21", "locAP", "citizen", "kyc"]) {
  console.log(k, "public_signals:", fixtures[k].public_signals);
}
console.log("Wrote", FIXTURES_PATH);
